### PR TITLE
Feature/recharge discount link

### PR DESCRIPTION
**Pull request by DanPete**
## Recharge Discount Code Redirect

* ClickUp Task (if applicable): [SMART: Auto-applied discounts for direct-to-cart ReCharge links](https://app.clickup.com/t/121n5jb)
* Link to Preview Theme: Need to actually open my dev theme since cookies don't come along `SMART [Mon Dev DS]`

**Why this change needs to occur?**

Client wants to be able to add multiple items to cart with link and automatically apply discount for recharge to use.

**High level overview of changes:**

- Created a new page template the reads the search params
- If the search params includes variant id(s), check for discount_code.
- Store discount_code as a `discount_code` cookie on the `/` path so the cart will have access to the discount_code.
- Recharge already has code the looks for the presence of `discount_code` cookie and if it finds that cookie, it will apply it automatically in recharge checkout.

Preview the theme `SMART [Mon Dev DS]` and use this link https://smarternutrition.com/pages/lp-redirect?view=lp-redirect&id[]=32711753171041&id[]=31637517992033&quantity=1&properties[shipping_interval_frequency]=20&discount_code=DEVIN80 for testing

**Has this change been tested?**

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by DanPete** [comment]
@robalan just if you want to view the PR as well.

**Comment by robalan** [comment]
Task linked: [CU-121n5jb SMART: Auto-applied discounts for direct-to-cart ReCharge links](https://app.clickup.com/t/121n5jb)

**Comment by surfwoodroad** [comment]
Looks great - nice and simple!

**Comment by DanPete** [comment]
> Looks great - nice and simple!

Thanks!

**Pull request merged**
